title: PagesTest
description: GitHub Pages で初めてブログを作成
url: "https://miyasato.github.io/PagesTest/"
baseurl: ""

# Author information
author:
  name: Keitan
  email: miyasato@wince.ne.jp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
